language: pillar
install:
  - set -xv
  - sudo apt-get install libc6-i386 texlive-latex-base texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra texlive-bibtex-extra
  - ./download.sh

script:
  - ./compile.sh
